{
    "watchdog_cmd": [
        "+ script_path=/data1/script/data-wi",
        "+++ dirname ./dhl_beijing_ruixing/.watc",
        "++ cd ./dhl_beijing_ruix",
        "++ ",
        "+ pushd /data/source/warehouse/dhl_beijing_ruixi",
        "+ read FILENA",
        "+ inotifywait -m -e close_write -e moved_to --format %f",
        "+ echo 2024-07-09.tar.",
        "+ [[ -f ./2024-07-09.tar.gz ",
        "+ [[ tar.gz == \\t\\a\\r\\.\\g\\z ",
        "++ ",
        "+ path=/data/source/warehouse/dhl_beijing_ruixi",
        "+ project=dhl_beijing_ruixi",
        "+ date_str=2024-07-",
        "+ [[ dhl_beijing_ruixing != '' ",
        "+ [[ 2024-07-09 != '' ",
        "+ echo 'unpack /data/source/warehouse/dhl_beijing_ruixing/2024-07-09.tar.g",
        "+ /data1/script/data-wise/unpack_data_from_project.sh 2024-07-09 dhl_beijing_ruixi",
        "+ echo 'stats indic ..",
        "+ /data1/script/data-wise/robot_stats_indic_project.sh All 2024-07-09 dhl_beijing_ruixi"
    ],
    "es_error": [
        {
            "errmsg": "extract_network_key_logs is 2024-07-01 project is dhl_beijing_ruixing",
            "es_action": null
        },
        {
            "errmsg": "extract_network_key_logs : ConnectionError((<urllib3.connection.HTTPSConnection object at 0x0000023F42871A50>, 'Connection to 192.168.190.128 timed out. (connect timeout=120)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPSConnection object at 0x0000023F42871A50>, 'Connection to 192.168.190.128 timed out. (connect timeout=120)'))",
            "es_action": null
        }
    ],
    "pyerr": [
        "gzip.BadGzipFile: Not a gzipped file (b'&\\x97')"
    ]
}